<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="AnyText" nsURI="http://github.com/NMFCode/NMF/AnyText" nsPrefix="anytext">
  <eClassifiers xsi:type="ecore:EClass" name="Grammar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Imports" upperBound="-1"
        eType="#//MetamodelImport" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Rules" lowerBound="1" upperBound="-1"
        eType="#//Rule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="StartRule" eType="#//Rule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
	<eStructuralFeatures xsi:type="ecore:EAttribute" name="TypeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
	<eStructuralFeatures xsi:type="ecore:EAttribute" name="Prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetamodelImport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="File" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Prefix" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelRule" eSuperTypes="#//ClassRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expression" lowerBound="1"
        eType="#//ParserExpression" containment="true"/>
  </eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="ParanthesisRule" eSuperTypes="#//ClassRule">
		<eStructuralFeatures xsi:type="ecore:EReference" name="OpeningParanthesis" lowerBound="1" upperBound="1"
			eType="#//KeywordExpression" containment="true"/>
		<eStructuralFeatures xsi:type="ecore:EReference" name="InnerRule" lowerBound="1" upperBound="1"
			eType="#//ClassRule"/>
		<eStructuralFeatures xsi:type="ecore:EReference" name="ClosingParanthesis" lowerBound="1" upperBound="1"
			eType="#//KeywordExpression" containment="true"/>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="FragmentRule" eSuperTypes="#//Rule">
		<eStructuralFeatures xsi:type="ecore:EReference" name="Expression" lowerBound="1"
			eType="#//ParserExpression" containment="true"/>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="ParserExpression" abstract="true">
		<eStructuralFeatures xsi:type="ecore:EAttribute" name="formattingInstructions"
			upperBound="-1" eType="#//FormattingInstruction"/>
	</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataRule" eSuperTypes="#//Rule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Regex" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InheritanceRule" eSuperTypes="#//ClassRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Subtypes" upperBound="-1"
        eType="#//ClassRule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassRule" abstract="true" eSuperTypes="#//Rule"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceExpression" eSuperTypes="#//ParserExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="InnerExpressions" lowerBound="2"
        upperBound="-1" eType="#//ParserExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryParserExpression" abstract="true"
      eSuperTypes="#//ParserExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Inner" lowerBound="1" eType="#//ParserExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlusExpression" eSuperTypes="#//UnaryParserExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="StarExpression" eSuperTypes="#//UnaryParserExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="MaybeExpression" eSuperTypes="#//UnaryParserExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="NegativeLookaheadExpression" eSuperTypes="#//UnaryParserExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="KeywordExpression" eSuperTypes="#//ParserExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Keyword" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChoiceExpression" eSuperTypes="#//ParserExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Alternatives" lowerBound="2"
        upperBound="-1" eType="#//ParserExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureExpression" abstract="true" eSuperTypes="#//ParserExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Feature" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Assigned" lowerBound="1"
        eType="#//ParserExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssignExpression" eSuperTypes="#//FeatureExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddAssignExpression" eSuperTypes="#//FeatureExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExistsAssignExpression" eSuperTypes="#//FeatureExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="RuleExpression" eSuperTypes="#//ParserExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Rule" lowerBound="1" eType="#//Rule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceExpression" eSuperTypes="#//ParserExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ReferencedRule" lowerBound="1"
        eType="#//ClassRule"/>
  </eClassifiers>
	<eClassifiers xsi:type="ecore:EEnum" name="FormattingInstruction">
		<eLiterals name="Newline"/>
		<eLiterals name="Indent" value="1"/>
		<eLiterals name="Unindent" value="2"/>
	</eClassifiers>
</ecore:EPackage>
