//------------------------------------------------------------------------------
// <auto-generated>
//     This Code was automatically created by the Atl2NmfS higher-order transformation.
//
//     Changes to this file can result in a wrong behavior and are discarded if the code is generated again.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Models;

namespace NMFExamples.PcmToMM06
{
    public class InputModelContainer
    {
    	public InputModelContainer(Model Environment) 
    	{
			this.Environment = Environment;
		}
		
		public Model Environment { get; private set; }
		
	}
}
