//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:6.0.26
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;


namespace AnyText.Test.Metamodel.Expressions
{
    
    
    /// <summary>
    /// The default implementation of the VariableExpression class
    /// </summary>
    [XmlNamespaceAttribute("anytext:exp")]
    [XmlNamespacePrefixAttribute("exp")]
    [ModelRepresentationClassAttribute("anytext:exp#//VariableExpression")]
    public partial class VariableExpression : Expression, IVariableExpression, IModelElement
    {
        
        /// <summary>
        /// The backing field for the Variable property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private string _variable;
        
        private static Lazy<ITypedElement> _variableAttribute = new Lazy<ITypedElement>(RetrieveVariableAttribute);
        
        private static IClass _classInstance;
        
        /// <summary>
        /// The variable property
        /// </summary>
        [DisplayNameAttribute("variable")]
        [CategoryAttribute("VariableExpression")]
        [XmlElementNameAttribute("variable")]
        [XmlAttributeAttribute(true)]
        public string Variable
        {
            get
            {
                return this._variable;
            }
            set
            {
                if ((this._variable != value))
                {
                    string old = this._variable;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnPropertyChanging("Variable", e, _variableAttribute);
                    this._variable = value;
                    this.OnPropertyChanged("Variable", e, _variableAttribute);
                }
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("anytext:exp#//VariableExpression")));
                }
                return _classInstance;
            }
        }
        
        private static ITypedElement RetrieveVariableAttribute()
        {
            return ((ITypedElement)(((ModelElement)(AnyText.Test.Metamodel.Expressions.VariableExpression.ClassInstance)).Resolve("variable")));
        }
        
        /// <summary>
        /// Resolves the given attribute name
        /// </summary>
        /// <returns>The attribute value or null if it could not be found</returns>
        /// <param name="attribute">The requested attribute name</param>
        /// <param name="index">The index of this attribute</param>
        protected override object GetAttributeValue(string attribute, int index)
        {
            if ((attribute == "VARIABLE"))
            {
                return this.Variable;
            }
            return base.GetAttributeValue(attribute, index);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "VARIABLE"))
            {
                this.Variable = ((string)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "VARIABLE"))
            {
                return new VariableProxy(this);
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("anytext:exp#//VariableExpression")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the variable property
        /// </summary>
        private sealed class VariableProxy : ModelPropertyChange<IVariableExpression, string>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public VariableProxy(IVariableExpression modelElement) : 
                    base(modelElement, "variable")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override string Value
            {
                get
                {
                    return this.ModelElement.Variable;
                }
                set
                {
                    this.ModelElement.Variable = value;
                }
            }
        }
    }
}
