//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:6.0.25
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace NMF.GlspTest.FiniteStateMachines
{
    
    
    /// <summary>
    /// The public interface for State
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(State))]
    [XmlDefaultImplementationTypeAttribute(typeof(State))]
    [ModelRepresentationClassAttribute("about:fsm#//State")]
    public interface IState : IModelElement
    {
        
        /// <summary>
        /// The name property
        /// </summary>
        [DisplayNameAttribute("name")]
        [CategoryAttribute("State")]
        [XmlElementNameAttribute("name")]
        [IdAttribute()]
        [XmlAttributeAttribute(true)]
        string Name
        {
            get;
            set;
        }
        
        /// <summary>
        /// The isFinalState property
        /// </summary>
        [TypeConverterAttribute(typeof(LowercaseBooleanConverter))]
        [DisplayNameAttribute("isFinalState")]
        [CategoryAttribute("State")]
        [XmlElementNameAttribute("isFinalState")]
        [XmlAttributeAttribute(true)]
        bool IsFinalState
        {
            get;
            set;
        }
        
        /// <summary>
        /// The outgoing property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("outgoing")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [XmlOppositeAttribute("source")]
        [ConstantAttribute()]
        IOrderedSetExpression<ITransition> Outgoing
        {
            get;
        }
        
        /// <summary>
        /// The incoming property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [DisplayNameAttribute("incoming")]
        [CategoryAttribute("State")]
        [XmlElementNameAttribute("incoming")]
        [XmlAttributeAttribute(true)]
        [XmlOppositeAttribute("target")]
        [ConstantAttribute()]
        IOrderedSetExpression<ITransition> Incoming
        {
            get;
        }
        
        /// <summary>
        /// Gets fired when the Name property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> NameChanged;
        
        /// <summary>
        /// Gets fired before the Name property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> NameChanging;
        
        /// <summary>
        /// Gets fired when the IsFinalState property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> IsFinalStateChanged;
        
        /// <summary>
        /// Gets fired before the IsFinalState property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> IsFinalStateChanging;
    }
}

