//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMFExamples.MM06;
using NMFExamples.MM06.SystemIndependent;
using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;


namespace NMFExamples.MM06.Assembly
{
    
    
    /// <summary>
    /// The default implementation of the DelegateConnector class
    /// </summary>
    [XmlNamespaceAttribute("http://sdq.ipd.kit.edu/ComponentBasedSystem/Assembly/")]
    [XmlNamespacePrefixAttribute("assembly")]
    public abstract partial class DelegateConnector : ModelElement, IDelegateConnector, IModelElement
    {
        
        private static Lazy<ITypedElement> _interfaceReference = new Lazy<ITypedElement>(RetrieveInterfaceReference);
        
        /// <summary>
        /// The backing field for the Interface property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private NMFExamples.MM06.SystemIndependent.IInterface _interface;
        
        private static Lazy<ITypedElement> _connectedAssemblyContextReference = new Lazy<ITypedElement>(RetrieveConnectedAssemblyContextReference);
        
        /// <summary>
        /// The backing field for the ConnectedAssemblyContext property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private NMFExamples.MM06.Assembly.IAssemblyContext _connectedAssemblyContext;
        
        private static IClass _classInstance;
        
        /// <summary>
        /// The Interface property
        /// </summary>
        [CategoryAttribute("DelegateConnector")]
        [XmlAttributeAttribute(true)]
        public NMFExamples.MM06.SystemIndependent.IInterface Interface
        {
            get
            {
                return this._interface;
            }
            set
            {
                if ((this._interface != value))
                {
                    NMFExamples.MM06.SystemIndependent.IInterface old = this._interface;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnInterfaceChanging(e);
                    this.OnPropertyChanging("Interface", e, _interfaceReference);
                    this._interface = value;
                    if ((old != null))
                    {
                        old.Deleted -= this.OnResetInterface;
                    }
                    if ((value != null))
                    {
                        value.Deleted += this.OnResetInterface;
                    }
                    this.OnInterfaceChanged(e);
                    this.OnPropertyChanged("Interface", e, _interfaceReference);
                }
            }
        }
        
        /// <summary>
        /// The ConnectedAssemblyContext property
        /// </summary>
        [CategoryAttribute("DelegateConnector")]
        [XmlAttributeAttribute(true)]
        public NMFExamples.MM06.Assembly.IAssemblyContext ConnectedAssemblyContext
        {
            get
            {
                return this._connectedAssemblyContext;
            }
            set
            {
                if ((this._connectedAssemblyContext != value))
                {
                    NMFExamples.MM06.Assembly.IAssemblyContext old = this._connectedAssemblyContext;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnConnectedAssemblyContextChanging(e);
                    this.OnPropertyChanging("ConnectedAssemblyContext", e, _connectedAssemblyContextReference);
                    this._connectedAssemblyContext = value;
                    if ((old != null))
                    {
                        old.Deleted -= this.OnResetConnectedAssemblyContext;
                    }
                    if ((value != null))
                    {
                        value.Deleted += this.OnResetConnectedAssemblyContext;
                    }
                    this.OnConnectedAssemblyContextChanged(e);
                    this.OnPropertyChanged("ConnectedAssemblyContext", e, _connectedAssemblyContextReference);
                }
            }
        }
        
        /// <summary>
        /// Gets the referenced model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> ReferencedElements
        {
            get
            {
                return base.ReferencedElements.Concat(new DelegateConnectorReferencedElementsCollection(this));
            }
        }
        
        /// <summary>
        /// Gets fired before the Interface property changes its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> InterfaceChanging;
        
        /// <summary>
        /// Gets fired when the Interface property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> InterfaceChanged;
        
        /// <summary>
        /// Gets fired before the ConnectedAssemblyContext property changes its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> ConnectedAssemblyContextChanging;
        
        /// <summary>
        /// Gets fired when the ConnectedAssemblyContext property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> ConnectedAssemblyContextChanged;
        
        private static ITypedElement RetrieveInterfaceReference()
        {
            return ((ITypedElement)(((ModelElement)(NMFExamples.MM06.Assembly.DelegateConnector.ClassInstance)).Resolve("Interface")));
        }
        
        /// <summary>
        /// Raises the InterfaceChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnInterfaceChanging(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.InterfaceChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the InterfaceChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnInterfaceChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.InterfaceChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Handles the event that the Interface property must reset
        /// </summary>
        /// <param name="sender">The object that sent this reset request</param>
        /// <param name="eventArgs">The event data for the reset event</param>
        private void OnResetInterface(object sender, EventArgs eventArgs)
        {
            if ((sender == this.Interface))
            {
                this.Interface = null;
            }
        }
        
        private static ITypedElement RetrieveConnectedAssemblyContextReference()
        {
            return ((ITypedElement)(((ModelElement)(NMFExamples.MM06.Assembly.DelegateConnector.ClassInstance)).Resolve("ConnectedAssemblyContext")));
        }
        
        /// <summary>
        /// Raises the ConnectedAssemblyContextChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnConnectedAssemblyContextChanging(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.ConnectedAssemblyContextChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the ConnectedAssemblyContextChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnConnectedAssemblyContextChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.ConnectedAssemblyContextChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Handles the event that the ConnectedAssemblyContext property must reset
        /// </summary>
        /// <param name="sender">The object that sent this reset request</param>
        /// <param name="eventArgs">The event data for the reset event</param>
        private void OnResetConnectedAssemblyContext(object sender, EventArgs eventArgs)
        {
            if ((sender == this.ConnectedAssemblyContext))
            {
                this.ConnectedAssemblyContext = null;
            }
        }
        
        /// <summary>
        /// Resolves the given URI to a child model element
        /// </summary>
        /// <returns>The model element or null if it could not be found</returns>
        /// <param name="reference">The requested reference name</param>
        /// <param name="index">The index of this reference</param>
        protected override IModelElement GetModelElementForReference(string reference, int index)
        {
            if ((reference == "INTERFACE"))
            {
                return this.Interface;
            }
            if ((reference == "CONNECTEDASSEMBLYCONTEXT"))
            {
                return this.ConnectedAssemblyContext;
            }
            return base.GetModelElementForReference(reference, index);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "INTERFACE"))
            {
                this.Interface = ((NMFExamples.MM06.SystemIndependent.IInterface)(value));
                return;
            }
            if ((feature == "CONNECTEDASSEMBLYCONTEXT"))
            {
                this.ConnectedAssemblyContext = ((NMFExamples.MM06.Assembly.IAssemblyContext)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given reference
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="reference">The requested reference in upper case</param>
        protected override NMF.Expressions.INotifyExpression<NMF.Models.IModelElement> GetExpressionForReference(string reference)
        {
            if ((reference == "INTERFACE"))
            {
                return new InterfaceProxy(this);
            }
            if ((reference == "CONNECTEDASSEMBLYCONTEXT"))
            {
                return new ConnectedAssemblyContextProxy(this);
            }
            return base.GetExpressionForReference(reference);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            throw new NotSupportedException("DelegateConnector does not have an absolute URI and therefore cannot be resolved.");
        }
        
        /// <summary>
        /// The collection class to to represent the children of the DelegateConnector class
        /// </summary>
        public class DelegateConnectorReferencedElementsCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private DelegateConnector _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public DelegateConnectorReferencedElementsCollection(DelegateConnector parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    if ((this._parent.Interface != null))
                    {
                        count = (count + 1);
                    }
                    if ((this._parent.ConnectedAssemblyContext != null))
                    {
                        count = (count + 1);
                    }
                    return count;
                }
            }
            
            /// <summary>
            /// Creates dependencies for the given collection
            /// </summary>
            /// <returns>A collection of dependencies</returns>
            protected override INotifiable[] CreateDependencies()
            {
                return new INotifiable[] {
                        new InterfaceProxy(this._parent),
                        new ConnectedAssemblyContextProxy(this._parent)};
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                if ((this._parent.Interface == null))
                {
                    NMFExamples.MM06.SystemIndependent.IInterface interfaceCasted = item.As<NMFExamples.MM06.SystemIndependent.IInterface>();
                    if ((interfaceCasted != null))
                    {
                        this._parent.Interface = interfaceCasted;
                        return;
                    }
                }
                if ((this._parent.ConnectedAssemblyContext == null))
                {
                    NMFExamples.MM06.Assembly.IAssemblyContext connectedAssemblyContextCasted = item.As<NMFExamples.MM06.Assembly.IAssemblyContext>();
                    if ((connectedAssemblyContextCasted != null))
                    {
                        this._parent.ConnectedAssemblyContext = connectedAssemblyContextCasted;
                        return;
                    }
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Interface = null;
                this._parent.ConnectedAssemblyContext = null;
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if ((item == this._parent.Interface))
                {
                    return true;
                }
                if ((item == this._parent.ConnectedAssemblyContext))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                if ((this._parent.Interface != null))
                {
                    array[arrayIndex] = this._parent.Interface;
                    arrayIndex = (arrayIndex + 1);
                }
                if ((this._parent.ConnectedAssemblyContext != null))
                {
                    array[arrayIndex] = this._parent.ConnectedAssemblyContext;
                    arrayIndex = (arrayIndex + 1);
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                if ((this._parent.Interface == item))
                {
                    this._parent.Interface = null;
                    return true;
                }
                if ((this._parent.ConnectedAssemblyContext == item))
                {
                    this._parent.ConnectedAssemblyContext = null;
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Interface).Concat(this._parent.ConnectedAssemblyContext).GetEnumerator();
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the Interface property
        /// </summary>
        private sealed class InterfaceProxy : ModelPropertyChange<IDelegateConnector, NMFExamples.MM06.SystemIndependent.IInterface>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public InterfaceProxy(IDelegateConnector modelElement) : 
                    base(modelElement, "Interface")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override NMFExamples.MM06.SystemIndependent.IInterface Value
            {
                get
                {
                    return this.ModelElement.Interface;
                }
                set
                {
                    this.ModelElement.Interface = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the ConnectedAssemblyContext property
        /// </summary>
        private sealed class ConnectedAssemblyContextProxy : ModelPropertyChange<IDelegateConnector, NMFExamples.MM06.Assembly.IAssemblyContext>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public ConnectedAssemblyContextProxy(IDelegateConnector modelElement) : 
                    base(modelElement, "ConnectedAssemblyContext")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override NMFExamples.MM06.Assembly.IAssemblyContext Value
            {
                get
                {
                    return this.ModelElement.ConnectedAssemblyContext;
                }
                set
                {
                    this.ModelElement.ConnectedAssemblyContext = value;
                }
            }
        }
    }
}
