//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using global::System.Collections;
using global::System.Collections.Generic;
using global::System.Collections.ObjectModel;
using global::System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace NMFExamples.Units
{
    
    
    /// <summary>
    /// The public interface for UnitCarryingElement
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(UnitCarryingElement))]
    [XmlDefaultImplementationTypeAttribute(typeof(UnitCarryingElement))]
    public interface IUnitCarryingElement : IModelElement
    {
        
        /// <summary>
        /// The unitSpecification property
        /// </summary>
        string UnitSpecification
        {
            get;
            set;
        }
        
        /// <summary>
        /// The unit property
        /// </summary>
        IUnit Unit
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the UnitSpecification property changes its value
        /// </summary>
        event global::System.EventHandler<ValueChangedEventArgs> UnitSpecificationChanging;
        
        /// <summary>
        /// Gets fired when the UnitSpecification property changed its value
        /// </summary>
        event global::System.EventHandler<ValueChangedEventArgs> UnitSpecificationChanged;
        
        /// <summary>
        /// Gets fired before the Unit property changes its value
        /// </summary>
        event global::System.EventHandler<ValueChangedEventArgs> UnitChanging;
        
        /// <summary>
        /// Gets fired when the Unit property changed its value
        /// </summary>
        event global::System.EventHandler<ValueChangedEventArgs> UnitChanged;
    }
}

