//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;


namespace NMF.Interop.Ecore
{
    
    
    /// <summary>
    /// The public interface for EClass
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(EClass))]
    [XmlDefaultImplementationTypeAttribute(typeof(EClass))]
    [ModelRepresentationClassAttribute("http://www.eclipse.org/emf/2002/Ecore#//EClass")]
    public partial interface IEClass : IModelElement, IEClassifier
    {
        
        /// <summary>
        /// The abstract property
        /// </summary>
        [DisplayNameAttribute("abstract")]
        [CategoryAttribute("EClass")]
        [XmlElementNameAttribute("abstract")]
        [XmlAttributeAttribute(true)]
        Nullable<bool> Abstract
        {
            get;
            set;
        }
        
        /// <summary>
        /// The interface property
        /// </summary>
        [DisplayNameAttribute("interface")]
        [CategoryAttribute("EClass")]
        [XmlElementNameAttribute("interface")]
        [XmlAttributeAttribute(true)]
        Nullable<bool> Interface
        {
            get;
            set;
        }
        
        /// <summary>
        /// The eSuperTypes property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [DisplayNameAttribute("eSuperTypes")]
        [CategoryAttribute("EClass")]
        [XmlElementNameAttribute("eSuperTypes")]
        [XmlAttributeAttribute(true)]
        [ConstantAttribute()]
        IOrderedSetExpression<IEClass> ESuperTypes
        {
            get;
        }
        
        /// <summary>
        /// The eOperations property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("eOperations")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [XmlOppositeAttribute("eContainingClass")]
        [ConstantAttribute()]
        IOrderedSetExpression<IEOperation> EOperations
        {
            get;
        }
        
        /// <summary>
        /// The eStructuralFeatures property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("eStructuralFeatures")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [XmlOppositeAttribute("eContainingClass")]
        [ConstantAttribute()]
        IOrderedSetExpression<IEStructuralFeature> EStructuralFeatures
        {
            get;
        }
        
        /// <summary>
        /// The eGenericSuperTypes property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("eGenericSuperTypes")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [ConstantAttribute()]
        IOrderedSetExpression<IEGenericType> EGenericSuperTypes
        {
            get;
        }
        
        /// <summary>
        /// Gets fired before the operation isSuperTypeOf gets called
        /// </summary>
        event EventHandler<OperationCallEventArgs> IsSuperTypeOfCalling;
        
        /// <summary>
        /// Gets fired after the operation isSuperTypeOf got called
        /// </summary>
        event EventHandler<OperationCallEventArgs> IsSuperTypeOfCalled;
        
        /// <summary>
        /// Gets fired before the operation getFeatureCount gets called
        /// </summary>
        event EventHandler<OperationCallEventArgs> GetFeatureCountCalling;
        
        /// <summary>
        /// Gets fired after the operation getFeatureCount got called
        /// </summary>
        event EventHandler<OperationCallEventArgs> GetFeatureCountCalled;
        
        /// <summary>
        /// Gets fired before the operation getFeatureID gets called
        /// </summary>
        event EventHandler<OperationCallEventArgs> GetFeatureIDCalling;
        
        /// <summary>
        /// Gets fired after the operation getFeatureID got called
        /// </summary>
        event EventHandler<OperationCallEventArgs> GetFeatureIDCalled;
        
        /// <summary>
        /// Gets fired before the operation getEStructuralFeature gets called
        /// </summary>
        event EventHandler<OperationCallEventArgs> GetEStructuralFeatureCalling;
        
        /// <summary>
        /// Gets fired before the operation getEStructuralFeature gets called
        /// </summary>
        event EventHandler<OperationCallEventArgs> GetEStructuralFeatureCalling_;
        
        /// <summary>
        /// Gets fired after the operation getEStructuralFeature got called
        /// </summary>
        event EventHandler<OperationCallEventArgs> GetEStructuralFeatureCalled;
        
        /// <summary>
        /// Gets fired after the operation getEStructuralFeature got called
        /// </summary>
        event EventHandler<OperationCallEventArgs> GetEStructuralFeatureCalled_;
        
        /// <summary>
        /// Gets fired before the operation getOperationCount gets called
        /// </summary>
        event EventHandler<OperationCallEventArgs> GetOperationCountCalling;
        
        /// <summary>
        /// Gets fired after the operation getOperationCount got called
        /// </summary>
        event EventHandler<OperationCallEventArgs> GetOperationCountCalled;
        
        /// <summary>
        /// Gets fired before the operation getEOperation gets called
        /// </summary>
        event EventHandler<OperationCallEventArgs> GetEOperationCalling;
        
        /// <summary>
        /// Gets fired after the operation getEOperation got called
        /// </summary>
        event EventHandler<OperationCallEventArgs> GetEOperationCalled;
        
        /// <summary>
        /// Gets fired before the operation getOperationID gets called
        /// </summary>
        event EventHandler<OperationCallEventArgs> GetOperationIDCalling;
        
        /// <summary>
        /// Gets fired after the operation getOperationID got called
        /// </summary>
        event EventHandler<OperationCallEventArgs> GetOperationIDCalled;
        
        /// <summary>
        /// Gets fired before the operation getOverride gets called
        /// </summary>
        event EventHandler<OperationCallEventArgs> GetOverrideCalling;
        
        /// <summary>
        /// Gets fired after the operation getOverride got called
        /// </summary>
        event EventHandler<OperationCallEventArgs> GetOverrideCalled;
        
        /// <summary>
        /// Gets fired when the Abstract property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> AbstractChanged;
        
        /// <summary>
        /// Gets fired before the Abstract property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> AbstractChanging;
        
        /// <summary>
        /// Gets fired when the Interface property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> InterfaceChanged;
        
        /// <summary>
        /// Gets fired before the Interface property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> InterfaceChanging;
        
        /// <summary>
        /// 
        /// </summary>
        /// <param name="someClass"></param>
        bool IsSuperTypeOf(IEClass someClass);
        
        /// <summary>
        /// 
        /// </summary>
        int GetFeatureCount();
        
        /// <summary>
        /// 
        /// </summary>
        /// <param name="featureID"></param>
        IEStructuralFeature GetEStructuralFeature(int featureID);
        
        /// <summary>
        /// 
        /// </summary>
        /// <param name="feature"></param>
        int GetFeatureID(IEStructuralFeature feature);
        
        /// <summary>
        /// 
        /// </summary>
        /// <param name="featureName"></param>
        IEStructuralFeature GetEStructuralFeature(string featureName);
        
        /// <summary>
        /// 
        /// </summary>
        int GetOperationCount();
        
        /// <summary>
        /// 
        /// </summary>
        /// <param name="operationID"></param>
        IEOperation GetEOperation(int operationID);
        
        /// <summary>
        /// 
        /// </summary>
        /// <param name="operation"></param>
        int GetOperationID(IEOperation operation);
        
        /// <summary>
        /// 
        /// </summary>
        /// <param name="operation"></param>
        IEOperation GetOverride(IEOperation operation);
    }
}
