//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMFExamples.Pcm.Core;
using NMFExamples.Pcm.Core.Entity;
using NMFExamples.Pcm.Parameter;
using NMFExamples.Pcm.Protocol;
using NMFExamples.Pcm.Reliability;
using NMFExamples.Pcm.Resourcetype;
using NMFExamples.Pcm.Seff;
using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using global::System.Collections;
using global::System.Collections.Generic;
using global::System.Collections.ObjectModel;
using global::System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Linq;

namespace NMFExamples.Pcm.Repository
{
    
    
    /// <summary>
    /// The public interface for InnerDeclaration
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(InnerDeclaration))]
    [XmlDefaultImplementationTypeAttribute(typeof(InnerDeclaration))]
    public interface IInnerDeclaration : IModelElement, INamedElement
    {
        
        /// <summary>
        /// The datatype_InnerDeclaration property
        /// </summary>
        IDataType Datatype_InnerDeclaration
        {
            get;
            set;
        }
        
        /// <summary>
        /// The compositeDataType_InnerDeclaration property
        /// </summary>
        ICompositeDataType CompositeDataType_InnerDeclaration
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the Datatype_InnerDeclaration property changes its value
        /// </summary>
        event global::System.EventHandler<ValueChangedEventArgs> Datatype_InnerDeclarationChanging;
        
        /// <summary>
        /// Gets fired when the Datatype_InnerDeclaration property changed its value
        /// </summary>
        event global::System.EventHandler<ValueChangedEventArgs> Datatype_InnerDeclarationChanged;
        
        /// <summary>
        /// Gets fired before the CompositeDataType_InnerDeclaration property changes its value
        /// </summary>
        event global::System.EventHandler<ValueChangedEventArgs> CompositeDataType_InnerDeclarationChanging;
        
        /// <summary>
        /// Gets fired when the CompositeDataType_InnerDeclaration property changed its value
        /// </summary>
        event global::System.EventHandler<ValueChangedEventArgs> CompositeDataType_InnerDeclarationChanged;
    }
}

