//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using NMFExamples.Identifier;
using NMFExamples.Pcm.Core;
using NMFExamples.Pcm.Core.Entity;
using NMFExamples.Pcm.Parameter;
using NMFExamples.Pcm.Reliability;
using NMFExamples.Pcm.Repository;
using NMFExamples.Pcm.Seff.Seff_performance;
using NMFExamples.Pcm.Seff.Seff_reliability;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;


namespace NMFExamples.Pcm.Seff
{
    
    
    /// <summary>
    /// The public interface for LoopAction
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(LoopAction))]
    [XmlDefaultImplementationTypeAttribute(typeof(LoopAction))]
    [ModelRepresentationClassAttribute("http://sdq.ipd.uka.de/PalladioComponentModel/5.0#//seff/LoopAction")]
    public partial interface ILoopAction : IModelElement, IAbstractLoopAction
    {
        
        /// <summary>
        /// The iterationCount_LoopAction property
        /// </summary>
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("iterationCount_LoopAction")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [XmlOppositeAttribute("loopAction_PCMRandomVariable")]
        IPCMRandomVariable IterationCount_LoopAction
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the IterationCount_LoopAction property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> IterationCount_LoopActionChanging;
        
        /// <summary>
        /// Gets fired when the IterationCount_LoopAction property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> IterationCount_LoopActionChanged;
    }
}
