<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="architectureCRA" nsURI="http://momot.big.tuwien.ac.at/architectureCRA/1.0"
    nsPrefix="architectureCRA">
  <eClassifiers xsi:type="ecore:EClass" name="ClassModel" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" ordered="true"
        upperBound="-1" eType="#//Class" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" ordered="true"
        upperBound="-1" eType="#//Feature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="encapsulates" lowerBound="1"
        upperBound="-1" eType="#//Feature" eOpposite="#//Feature/isEncapsulatedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//Feature"/>
  <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataDependency" upperBound="-1"
        eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionalDependency" upperBound="-1"
        eType="#//Method"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isEncapsulatedBy" eType="#//Class"
        eOpposite="#//Class/encapsulates"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>