//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:6.0.26
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;


namespace NMF.Models.Meta
{
    
    
    [ModelRepresentationClassAttribute("http://nmf.codeplex.com/nmeta/#//IdentifierScope")]
    public enum IdentifierScope
    {
        
        /// <summary>
        ///The identifier scope is inherited from the (first) base class that defines an identifier
        ///</summary>
        Inherit = 0,
        
        /// <summary>
        ///The identifier has a local scope, i.e., the identifier identifies an element only in the scope of the parent element
        ///</summary>
        Local = 1,
        
        /// <summary>
        ///The identifier has a global scope, i.e., there is no other model element with the same identifier
        ///</summary>
        Global = 2,
    }
}
