//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;


namespace NMF.Models.Tests.Minimal_example.Product
{
    
    
    /// <summary>
    /// The public interface for ProductLibrary
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(ProductLibrary))]
    [XmlDefaultImplementationTypeAttribute(typeof(ProductLibrary))]
    [ModelRepresentationClassAttribute("http://www.example.org/minimal_example#//product/ProductLibrary")]
    public partial interface IProductLibrary : IModelElement
    {
        
        /// <summary>
        /// The products property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("products")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [ConstantAttribute()]
        IOrderedSetExpression<IProductDefinition> Products
        {
            get;
        }
    }
}
