//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;


namespace NMF.Models.Changes
{
    
    
    /// <summary>
    /// The public interface for AttributeListDeletion
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(AttributeListDeletion))]
    [XmlDefaultImplementationTypeAttribute(typeof(AttributeListDeletion))]
    [ModelRepresentationClassAttribute("http://nmf.codeplex.com/changes#//AttributeListDeletion")]
    public partial interface IAttributeListDeletion : NMF.Models.IModelElement, IAttributeChange
    {
        
        /// <summary>
        /// The deletedValue property
        /// </summary>
        [DisplayNameAttribute("deletedValue")]
        [CategoryAttribute("AttributeListDeletion")]
        [XmlElementNameAttribute("deletedValue")]
        [XmlAttributeAttribute(true)]
        string DeletedValue
        {
            get;
            set;
        }
        
        /// <summary>
        /// The index property
        /// </summary>
        [DisplayNameAttribute("index")]
        [CategoryAttribute("AttributeListDeletion")]
        [XmlElementNameAttribute("index")]
        [XmlAttributeAttribute(true)]
        int Index
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired when the DeletedValue property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> DeletedValueChanged;
        
        /// <summary>
        /// Gets fired before the DeletedValue property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> DeletedValueChanging;
        
        /// <summary>
        /// Gets fired when the Index property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> IndexChanged;
        
        /// <summary>
        /// Gets fired before the Index property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> IndexChanging;
    }
}
