//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:6.0.26
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Linq;


namespace NMF.Interop.Cmof
{
    
    
    /// <summary>
    /// The public interface for EnumerationLiteral
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(EnumerationLiteral))]
    [XmlDefaultImplementationTypeAttribute(typeof(EnumerationLiteral))]
    [ModelRepresentationClassAttribute("http://www.omg.org/spec/MOF/20131001/cmof.xmi#//EnumerationLiteral")]
    public interface IEnumerationLiteral : IModelElement, IInstanceSpecification
    {
        
        /// <summary>
        /// The Enumeration that this EnumerationLiteral is a member of.
        /// </summary>
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("enumeration")]
        [XmlAttributeAttribute(true)]
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Hidden)]
        [XmlOppositeAttribute("ownedLiteral")]
        NMF.Interop.Cmof.IEnumeration Enumeration
        {
            get;
            set;
        }
        
        /// <summary>
        /// classifier = enumeration
        /// </summary>
        /// <param name="diagnostics">The chain of diagnostics to which problems are to be appended.</param>
        /// <param name="context">The cache of context-specific information.</param>
        bool Classifier_equals_owning_enumeration(object diagnostics, object context);
    }
}
