//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMFExamples.Pcm.Core;
using NMFExamples.Pcm.Core.Composition;
using NMFExamples.Pcm.Core.Entity;
using NMFExamples.Pcm.Parameter;
using NMFExamples.Pcm.Repository;
using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;


namespace NMFExamples.Pcm.Usagemodel
{
    
    
    /// <summary>
    /// The default implementation of the Start class
    /// </summary>
    [XmlNamespaceAttribute("http://sdq.ipd.uka.de/PalladioComponentModel/UsageModel/5.0")]
    [XmlNamespacePrefixAttribute("usagemodel")]
    [DebuggerDisplayAttribute("Start {Id}")]
    public partial class Start : AbstractUserAction, IStart, IModelElement
    {
        
        private static Lazy<IOperation> _startHasNoPredecessorOperation = new Lazy<IOperation>(RetrieveStartHasNoPredecessorOperation);
        
        private static IClass _classInstance;
        
        /// <summary>
        /// Gets fired before the operation StartHasNoPredecessor gets called
        /// </summary>
        public event EventHandler<OperationCallEventArgs> StartHasNoPredecessorCalling;
        
        /// <summary>
        /// Gets fired after the operation StartHasNoPredecessor got called
        /// </summary>
        public event EventHandler<OperationCallEventArgs> StartHasNoPredecessorCalled;
        
        /// <summary>
        /// 
        /// </summary>
        /// <param name="diagnostics"></param>
        /// <param name="context"></param>
        public bool StartHasNoPredecessor(object diagnostics, object context)
        {
            Func<IStart, object, object, bool> handler = OperationBroker.Instance.GetRegisteredDelegate<Func<IStart, object, object, bool>>(_startHasNoPredecessorOperation);
            if ((handler != null))
            {
            }
            else
            {
                throw new InvalidOperationException(("There is no implementation for method StartHasNoPredecessor registered. Use the m" +
                        "ethod broker to register a method implementation."));
            }
            OperationCallEventArgs e = new OperationCallEventArgs(this, _startHasNoPredecessorOperation.Value, diagnostics, context);
            this.OnStartHasNoPredecessorCalling(e);
            this.OnBubbledChange(BubbledChangeEventArgs.OperationCalling(this, _startHasNoPredecessorOperation.Value, e));
            bool result = handler.Invoke(this, diagnostics, context);
            e.Result = result;
            this.OnStartHasNoPredecessorCalled(e);
            this.OnBubbledChange(BubbledChangeEventArgs.OperationCalled(this, _startHasNoPredecessorOperation.Value, e));
            return result;
        }
        
        private static IOperation RetrieveStartHasNoPredecessorOperation()
        {
            return ClassInstance.LookupOperation("StartHasNoPredecessor");
        }
        
        /// <summary>
        /// Raises the StartHasNoPredecessorCalling event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnStartHasNoPredecessorCalling(OperationCallEventArgs eventArgs)
        {
            EventHandler<OperationCallEventArgs> handler = this.StartHasNoPredecessorCalling;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the StartHasNoPredecessorCalled event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnStartHasNoPredecessorCalled(OperationCallEventArgs eventArgs)
        {
            EventHandler<OperationCallEventArgs> handler = this.StartHasNoPredecessorCalled;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            throw new NotSupportedException("Start does not have an absolute URI and therefore cannot be resolved.");
        }
    }
}
