using System;

namespace NMF.Expressions
{
    internal sealed partial class ObservableExpressionTypes
	{
        public static readonly Type[] ObservableNewExpression =
        {
            typeof(ObservableNewExpression<,>),
            typeof(ObservableNewExpression<,,>),
            typeof(ObservableNewExpression<,,,>),
            typeof(ObservableNewExpression<,,,,>),
            typeof(ObservableNewExpression<,,,,,>),
            typeof(ObservableNewExpression<,,,,,,>),
            typeof(ObservableNewExpression<,,,,,,,>),
            typeof(ObservableNewExpression<,,,,,,,,>),
            typeof(ObservableNewExpression<,,,,,,,,,>),
            typeof(ObservableNewExpression<,,,,,,,,,,>),
            typeof(ObservableNewExpression<,,,,,,,,,,,>),
            typeof(ObservableNewExpression<,,,,,,,,,,,,>),
            typeof(ObservableNewExpression<,,,,,,,,,,,,,>),
            typeof(ObservableNewExpression<,,,,,,,,,,,,,,>),
            typeof(ObservableNewExpression<,,,,,,,,,,,,,,,>)
        };
        public static readonly Type[] ObservableStaticMethodCall =
        {
            typeof(ObservableStaticMethodCall<,>),
            typeof(ObservableStaticMethodCall<,,>),
            typeof(ObservableStaticMethodCall<,,,>),
            typeof(ObservableStaticMethodCall<,,,,>),
            typeof(ObservableStaticMethodCall<,,,,,>),
            typeof(ObservableStaticMethodCall<,,,,,,>),
            typeof(ObservableStaticMethodCall<,,,,,,,>),
            typeof(ObservableStaticMethodCall<,,,,,,,,>),
            typeof(ObservableStaticMethodCall<,,,,,,,,,>),
            typeof(ObservableStaticMethodCall<,,,,,,,,,,>),
            typeof(ObservableStaticMethodCall<,,,,,,,,,,,>),
            typeof(ObservableStaticMethodCall<,,,,,,,,,,,,>),
            typeof(ObservableStaticMethodCall<,,,,,,,,,,,,,>),
            typeof(ObservableStaticMethodCall<,,,,,,,,,,,,,,>),
            typeof(ObservableStaticMethodCall<,,,,,,,,,,,,,,,>)
        };
        public static readonly Type[] ObservableStaticLensMethodCall =
        {
            typeof(ObservableStaticLensMethodCall<,>),
            typeof(ObservableStaticLensMethodCall<,,>),
            typeof(ObservableStaticLensMethodCall<,,,>),
            typeof(ObservableStaticLensMethodCall<,,,,>),
            typeof(ObservableStaticLensMethodCall<,,,,,>),
            typeof(ObservableStaticLensMethodCall<,,,,,,>),
            typeof(ObservableStaticLensMethodCall<,,,,,,,>),
            typeof(ObservableStaticLensMethodCall<,,,,,,,,>),
            typeof(ObservableStaticLensMethodCall<,,,,,,,,,>),
            typeof(ObservableStaticLensMethodCall<,,,,,,,,,,>),
            typeof(ObservableStaticLensMethodCall<,,,,,,,,,,,>),
            typeof(ObservableStaticLensMethodCall<,,,,,,,,,,,,>),
            typeof(ObservableStaticLensMethodCall<,,,,,,,,,,,,,>),
            typeof(ObservableStaticLensMethodCall<,,,,,,,,,,,,,,>),
            typeof(ObservableStaticLensMethodCall<,,,,,,,,,,,,,,,>)
        };
        public static readonly Type[] ObservableMethodCall =
        {
            typeof(ObservableMethodCall<,>),
            typeof(ObservableMethodCall<,,>),
            typeof(ObservableMethodCall<,,,>),
            typeof(ObservableMethodCall<,,,,>),
            typeof(ObservableMethodCall<,,,,,>),
            typeof(ObservableMethodCall<,,,,,,>),
            typeof(ObservableMethodCall<,,,,,,,>),
            typeof(ObservableMethodCall<,,,,,,,,>),
            typeof(ObservableMethodCall<,,,,,,,,,>),
            typeof(ObservableMethodCall<,,,,,,,,,,>),
            typeof(ObservableMethodCall<,,,,,,,,,,,>),
            typeof(ObservableMethodCall<,,,,,,,,,,,,>),
            typeof(ObservableMethodCall<,,,,,,,,,,,,,>),
            typeof(ObservableMethodCall<,,,,,,,,,,,,,,>),
            typeof(ObservableMethodCall<,,,,,,,,,,,,,,,>)
        };
        public static readonly Type[] ObservableLensMethodCall =
        {
            typeof(ObservableLensMethodCall<,>),
            typeof(ObservableLensMethodCall<,,>),
            typeof(ObservableLensMethodCall<,,,>),
            typeof(ObservableLensMethodCall<,,,,>),
            typeof(ObservableLensMethodCall<,,,,,>),
            typeof(ObservableLensMethodCall<,,,,,,>),
            typeof(ObservableLensMethodCall<,,,,,,,>),
            typeof(ObservableLensMethodCall<,,,,,,,,>),
            typeof(ObservableLensMethodCall<,,,,,,,,,>),
            typeof(ObservableLensMethodCall<,,,,,,,,,,>),
            typeof(ObservableLensMethodCall<,,,,,,,,,,,>),
            typeof(ObservableLensMethodCall<,,,,,,,,,,,,>),
            typeof(ObservableLensMethodCall<,,,,,,,,,,,,,>),
            typeof(ObservableLensMethodCall<,,,,,,,,,,,,,,>),
            typeof(ObservableLensMethodCall<,,,,,,,,,,,,,,,>)
        };
        public static readonly Type[] ObservableStaticProxyCall =
        {
            typeof(ObservableStaticProxyCall<,>),
            typeof(ObservableStaticProxyCall<,,>),
            typeof(ObservableStaticProxyCall<,,,>),
            typeof(ObservableStaticProxyCall<,,,,>),
            typeof(ObservableStaticProxyCall<,,,,,>),
            typeof(ObservableStaticProxyCall<,,,,,,>),
            typeof(ObservableStaticProxyCall<,,,,,,,>),
            typeof(ObservableStaticProxyCall<,,,,,,,,>),
            typeof(ObservableStaticProxyCall<,,,,,,,,,>),
            typeof(ObservableStaticProxyCall<,,,,,,,,,,>),
            typeof(ObservableStaticProxyCall<,,,,,,,,,,,>),
            typeof(ObservableStaticProxyCall<,,,,,,,,,,,,>),
            typeof(ObservableStaticProxyCall<,,,,,,,,,,,,,>),
            typeof(ObservableStaticProxyCall<,,,,,,,,,,,,,,>),
            typeof(ObservableStaticProxyCall<,,,,,,,,,,,,,,,>)
        };
        public static readonly Type[] ObservableMethodProxyCall =
        {
            typeof(ObservableMethodProxyCall<,>),
            typeof(ObservableMethodProxyCall<,,>),
            typeof(ObservableMethodProxyCall<,,,>),
            typeof(ObservableMethodProxyCall<,,,,>),
            typeof(ObservableMethodProxyCall<,,,,,>),
            typeof(ObservableMethodProxyCall<,,,,,,>),
            typeof(ObservableMethodProxyCall<,,,,,,,>),
            typeof(ObservableMethodProxyCall<,,,,,,,,>),
            typeof(ObservableMethodProxyCall<,,,,,,,,,>),
            typeof(ObservableMethodProxyCall<,,,,,,,,,,>),
            typeof(ObservableMethodProxyCall<,,,,,,,,,,,>),
            typeof(ObservableMethodProxyCall<,,,,,,,,,,,,>),
            typeof(ObservableMethodProxyCall<,,,,,,,,,,,,,>),
            typeof(ObservableMethodProxyCall<,,,,,,,,,,,,,,>),
            typeof(ObservableMethodProxyCall<,,,,,,,,,,,,,,,>),
            typeof(ObservableMethodProxyCall<,,,,,,,,,,,,,,,,>)
        };
        public static readonly Type[] ObservableStaticLensProxyCall =
        {
            typeof(ObservableStaticLensProxyCall<,>),
            typeof(ObservableStaticLensProxyCall<,,>),
            typeof(ObservableStaticLensProxyCall<,,,>),
            typeof(ObservableStaticLensProxyCall<,,,,>),
            typeof(ObservableStaticLensProxyCall<,,,,,>),
            typeof(ObservableStaticLensProxyCall<,,,,,,>),
            typeof(ObservableStaticLensProxyCall<,,,,,,,>),
            typeof(ObservableStaticLensProxyCall<,,,,,,,,>),
            typeof(ObservableStaticLensProxyCall<,,,,,,,,,>),
            typeof(ObservableStaticLensProxyCall<,,,,,,,,,,>),
            typeof(ObservableStaticLensProxyCall<,,,,,,,,,,,>),
            typeof(ObservableStaticLensProxyCall<,,,,,,,,,,,,>),
            typeof(ObservableStaticLensProxyCall<,,,,,,,,,,,,,>),
            typeof(ObservableStaticLensProxyCall<,,,,,,,,,,,,,,>)
        };
        public static readonly Type[] ObservableMethodLensProxyCall =
        {
            typeof(ObservableMethodLensProxyCall<,>),
            typeof(ObservableMethodLensProxyCall<,,>),
            typeof(ObservableMethodLensProxyCall<,,,>),
            typeof(ObservableMethodLensProxyCall<,,,,>),
            typeof(ObservableMethodLensProxyCall<,,,,,>),
            typeof(ObservableMethodLensProxyCall<,,,,,,>),
            typeof(ObservableMethodLensProxyCall<,,,,,,,>),
            typeof(ObservableMethodLensProxyCall<,,,,,,,,>),
            typeof(ObservableMethodLensProxyCall<,,,,,,,,,>),
            typeof(ObservableMethodLensProxyCall<,,,,,,,,,,>),
            typeof(ObservableMethodLensProxyCall<,,,,,,,,,,,>),
            typeof(ObservableMethodLensProxyCall<,,,,,,,,,,,,>),
            typeof(ObservableMethodLensProxyCall<,,,,,,,,,,,,,>),
            typeof(ObservableMethodLensProxyCall<,,,,,,,,,,,,,,>),
            typeof(ObservableMethodLensProxyCall<,,,,,,,,,,,,,,,>)
        };
        public static readonly Type[] ObservingFunc =
        {
            typeof(ObservingFunc<,>),
            typeof(ObservingFunc<,,>),
            typeof(ObservingFunc<,,,>),
            typeof(ObservingFunc<,,,,>),
            typeof(ObservingFunc<,,,,,>),
            typeof(ObservingFunc<,,,,,,>),
            typeof(ObservingFunc<,,,,,,,>),
            typeof(ObservingFunc<,,,,,,,,>),
            typeof(ObservingFunc<,,,,,,,,,>),
            typeof(ObservingFunc<,,,,,,,,,,>),
            typeof(ObservingFunc<,,,,,,,,,,,>),
            typeof(ObservingFunc<,,,,,,,,,,,,>),
            typeof(ObservingFunc<,,,,,,,,,,,,,>),
            typeof(ObservingFunc<,,,,,,,,,,,,,,>),
            typeof(ObservingFunc<,,,,,,,,,,,,,,,>)
        };
        public static readonly Type[] ObservableSimpleMethodProxyCall =
        {
            typeof(ObservableSimpleMethodProxyCall<,>),
            typeof(ObservableSimpleMethodProxyCall<,,>),
            typeof(ObservableSimpleMethodProxyCall<,,,>),
            typeof(ObservableSimpleMethodProxyCall<,,,,>),
            typeof(ObservableSimpleMethodProxyCall<,,,,,>),
            typeof(ObservableSimpleMethodProxyCall<,,,,,,>),
            typeof(ObservableSimpleMethodProxyCall<,,,,,,,>),
            typeof(ObservableSimpleMethodProxyCall<,,,,,,,,>),
            typeof(ObservableSimpleMethodProxyCall<,,,,,,,,,>),
            typeof(ObservableSimpleMethodProxyCall<,,,,,,,,,,>),
            typeof(ObservableSimpleMethodProxyCall<,,,,,,,,,,,>),
            typeof(ObservableSimpleMethodProxyCall<,,,,,,,,,,,,>),
            typeof(ObservableSimpleMethodProxyCall<,,,,,,,,,,,,,>),
            typeof(ObservableSimpleMethodProxyCall<,,,,,,,,,,,,,,>),
            typeof(ObservableSimpleMethodProxyCall<,,,,,,,,,,,,,,,>),
            typeof(ObservableSimpleMethodProxyCall<,,,,,,,,,,,,,,,,>)
        };
        public static readonly Type[] ObservableSimpleLensMethodProxyCall =
        {
            typeof(ObservableSimpleLensMethodProxyCall<,>),
            typeof(ObservableSimpleLensMethodProxyCall<,,>),
            typeof(ObservableSimpleLensMethodProxyCall<,,,>),
            typeof(ObservableSimpleLensMethodProxyCall<,,,,>),
            typeof(ObservableSimpleLensMethodProxyCall<,,,,,>),
            typeof(ObservableSimpleLensMethodProxyCall<,,,,,,>),
            typeof(ObservableSimpleLensMethodProxyCall<,,,,,,,>),
            typeof(ObservableSimpleLensMethodProxyCall<,,,,,,,,>),
            typeof(ObservableSimpleLensMethodProxyCall<,,,,,,,,,>),
            typeof(ObservableSimpleLensMethodProxyCall<,,,,,,,,,,>),
            typeof(ObservableSimpleLensMethodProxyCall<,,,,,,,,,,,>),
            typeof(ObservableSimpleLensMethodProxyCall<,,,,,,,,,,,,>),
            typeof(ObservableSimpleLensMethodProxyCall<,,,,,,,,,,,,,>),
            typeof(ObservableSimpleLensMethodProxyCall<,,,,,,,,,,,,,,>),
            typeof(ObservableSimpleLensMethodProxyCall<,,,,,,,,,,,,,,,>)
        };
	}
}